apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: entandocompositeapps.entando.org
spec:
  group: entando.org
  names:
    kind: EntandoCompositeApp
    plural: entandocompositeapps
    shortNames:
      - ecapps
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.entandoDeploymentPhase
        - name: Observed Generation
          type: number
          jsonPath: .status.observedGeneration
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dbmsOverride:
                  description: >
                    The database management system (DBMS) to use for persistence for every component deployed in
                    this EntandoCompositeApp. Can be any of mysql, oracle, postgresql or embedded. Each component
                    deployed in the EntandoCompositeApp will be evaluated and if it supports the standard 'spec.dbms'
                    property, the value of this property will be given to the component's 'spec.dbms'. Please consult
                    the documentation for each component's CRD to determine the exact semantics of this value.
                  type: string
                  pattern: '^(mysql|oracle|postgresql|embedded|none)$'
                ingressHostNameOverride:
                  description: >
                    The hostname that will be used to access every component deployed in this EntandoCompositeApp.
                    This is intended for scenarios where all the components need to be accessed from the same hostname,
                    such as when installing Kubernetes or Openshift locally on a laptop or desktop.Please consult
                    the documentation for each component's CRD for more information on the exact semantics of this value.
                  type: string
                  pattern: '^([A-Za-z0-9-]{1,63}\.)*[[A-Za-z0-9-]{1,63}$'
                tlsSecretNameOverride:
                  description: >
                    The name of a Kubernetes TLS Secret that will be used to enable TLS on the the hostname specified
                    in the property spec.ingressHostnameOverride. This TLS Secret  will be used for TLS on
                    every component deployed in this EntandoCompositeApp.Please consult
                    the documentation for each component's CRD for more information on the exact semantics of this value.
                  type: string
                  pattern: '^([A-Za-z0-9-]{1,63}\.)*[[A-Za-z0-9-]{1,63}$'
                components:
                  description: >
                    A list of Entando custom resources that need to be deployed in the sequence specified. Each entry in
                    this list can either be an inline declaration of an Entando custom resource (e.g. EntandoKeycloakServer,
                    EntandoApp), or it can be a reference to an Entando custom resource that is created separately.

                    When the Entando custom resource is created separately, it will typically be annotated with annotation value
                    'entando.org/processing-instruction=defer'. This instructs the Entando Operator not to process
                    this item when it is updated, but only when the EntandoCompositeApp it is referenced from is updated.
                    This is useful for scenarios where the first deployment of a set of Entando custom resource manifests
                    needs to be processed in a specific sequence, but subsequent updates need to be applied individually.
                    By removing the 'entando.org/processing-instruction' instruction, the deployer will allow the
                    Entando Operator to process the referenced resources directly.
                  type: array
                  items:
                    type: object
                    description: >
                    properties:
                      kind:
                        description: >
                          Can be one of EntandoKeycloakServer, EntandoClusterInfrastructure, EntandoApp, EntandoPlugin
                          EntandoDatabaseService, EntandoAppPluginLink or EntandoCustomResourceReference. This field
                          is used to determine the structure of the 'spec' object to follow.
                        type: string
                      spec:
                        x-kubernetes-preserve-unknown-fields: true
                        description: >
                          For items of kind EntandoKeycloakServer, EntandoClusterInfrastructure, EntandoApp,
                          EntandoPlugin, EntandoDatabaseService and EntandoAppPluginLink, please refer to the
                          CRD associated with each of these resource kinds as guidance how to populate the spec.
                          For the EntandoCustomResourceReference, the structure is as follows:
                          targetKind:string   The kind of Entando custom resource being referenced
                          targetNamespace:string  The namespace of the Entando custom resource being referenced
                          targetName:string The name of the Entando custom resource being referenced
                        type: object
                      metadata:
                        x-kubernetes-preserve-unknown-fields: true
                        description: >
                          This is an object containing the standard Kubernetes metadata associated with the Entando
                          custom resource.
                        type: object
                        properties:
                          name:
                            type: string
                            description: The name to use for the inline Entando custom resource
                          namespace:
                            type: string
                            description: >
                              The namespace where  the inline Entando custom resource will be created. If this field
                              is omitted, the inline Entando custom resource will be created in the same namespace
                              as this EntandoCompositeApp.
            status:
              type: object
              properties:
                observedGeneration:
                  type: number
                entandoDeploymentPhase:
                  type: string
                serverStatuses:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
